spring:
  application:
    name: recon
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/recon}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}